<?php 

/**
* Implements hook_block_info().
*/
function fondexx_block_info() {
  $blocks = array();
  $blocks['Fondexx market leaders'] = array(
    'info' => t('Fondexx market leaders'),
  );

  return $blocks;
}

/**
* Implements hook_block_view().
*/
function fondexx_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'Fondexx market leaders':
      $block['subject'] = '';
      $block['content'] = _fondexx_market_leaders_form_block();
      break;
  }

  return $block;
}

function fondexx_form_alter(&$form, &$form_state, $form_id) {
    if ($form['#id'] == 'webform-client-form-177') {
        dsm($form, drupal_get_title());
        $form['submitted']['otkuda_prishel']['#default_value'] = drupal_get_title();

        if (request_path() == 'study/start') {
            $form['actions']['submit']['#value']  = t('Undergo free');
        } else if (request_path() == 'trade/demo') {
            $form['actions']['submit']['#value']  = t('Create demo account');
        } else {
            $form['actions']['submit']['#value'] = t('Get access');
        }
    }
}

function _fondexx_market_leaders_form_block() {
    $output = "<h2>Market leaders goes here! (soon)</h2>- TODO -";
    return $output;
}